name: New nuget realease step with semver

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Semantic Release
      uses: actions/checkout@v1
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        DOCKERHUB_LOGIN: ${{secrets.DOCKERHUB_LOGIN}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      with:
        extra_plugins: |
          @semantic-release/git@7.0.18
          @semantic-release/exec@3.3.8
          @semantic-release/changelog@3.0.0
    outputs:
      new_release_published: ${{ steps.semantic_dry.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_dry.outputs.new_release_version }}
