name: Semantic Versioning

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Conventional Commit Checker
      uses: agenthunt/conventional-commit-checker-action@v1.0.0
      with:
        pr-title-regex::  "^(feat|fix|ci|chore|docs|test|style|refactor)((.+?))?: .{1,}$"
        pr-body-regex: "(.*)"


    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
